# Generated by Django 2.2.4 on 2019-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lession',
            new_name='Lesson',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='lession',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
